version: '3.8'
services:
  urban-order-db:
    image: postgres:15-alpine
    container_name: urban-order-db
    restart: always
    environment:
      POSTGRES_USER: urban_order_user
      POSTGRES_PASSWORD: urban_order_pass
      POSTGRES_DB: urban_order_db
    volumes:
      - ./DB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  urban-order-backend:
    build:
      context: ./Backend/
    container_name: urban-order-backend
    restart: always
    depends_on:
      urban-order-db:
        condition: service_healthy
    environment:
      DB_NAME: urban_order_db
      DB_USER: urban_order_user
      DB_PASSWORD: urban_order_pass
      DB_HOST: urban-order-db
      DB_PORT: 5432
    ports:
      - "5000:5000"
